#local_backend: true

backend:
  name: github
  repo: AlleyCorpNord/toboggan-website
  branch: decapcms

publish_mode: editorial_workflow

media_folder: 'app/public/media' # Media files will be stored in the repo under static/media
public_folder: '/media' # The src attribute for uploaded media will begin with /media

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, es, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: "Blog"
    label: "Blog Post"
    folder: "app/contents/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      # - label: "Author"
      #   name: "author"
      #   widget: "object"
      #   fields:
      #     - { label: "Name", name: "name", widget: "string" }
      #     - { label: "Picture", name: "picture", widget: "image" }
      # - label: "OG Image"
      #   name: "ogImage"
      #   widget: "object"
      #   fields:
      #     - { label: "URL", name: "url", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }