local_backend: true

backend:
  name: git-gateway

media_folder: 'app/public/media' # Media files will be stored in the repo under static/media
public_folder: '/media' # The src attribute for uploaded media will begin with /media

collections:
  - name: "Blog"
    label: "Blog Post"
    folder: "app/contents/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      # - label: "Author"
      #   name: "author"
      #   widget: "object"
      #   fields:
      #     - { label: "Name", name: "name", widget: "string" }
      #     - { label: "Picture", name: "picture", widget: "image" }
      # - label: "OG Image"
      #   name: "ogImage"
      #   widget: "object"
      #   fields:
      #     - { label: "URL", name: "url", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }