name: Translate EN blog posts to FR/ES on PRs

on:
  pull_request:
    branches:
      - decapcms
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: read

jobs:
  translate:
    name: Translate changed EN markdown files
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'cms/Blog/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install OpenAI SDK
        run: |
          npm install openai --no-save

      - name: Determine changed EN markdown files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            app/contents/blog/en/*.md

      - name: Show changed files (debug)
        run: |
          echo "Changed files:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
          done

      - name: Translate changed files to FR and ES
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          TRANSLATION_MODEL: gpt-5
        run: |
          node app/scripts/translate-blog.js

      - name: Commit and push translations
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(i18n): auto-translate EN blog posts to FR and ES"
          commit_user_name: toboggan-bot
          commit_user_email: bot@users.noreply.github.com
          file_pattern: |
            app/contents/blog/fr/*.md
            app/contents/blog/es/*.md


